language: python
git:
    quiet: true
    submodules: false
branches:
    only:
        - /.*/
python:
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'
#before_install:
#    - pip install lizard
script:
    - chmod 744 lint.sh && ./lint.sh
    - application/copyright --version
    - application/copyright --help
