language: python
git:
    quiet: true
    submodules: false
branches:
    only:
        - /.*/
python:
    - '3.6'
before_install:
    - pip install lizard
script:
    - chmod 744 lint.sh && ./lint.sh
    - application/copyright --version
    - application/copyright --help
